# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: mobiledevops/android-sdk-image:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - './gradlew clean assemble'

test:
  stage: test
  script:
    - './gradlew check'

deploy:
  stage: deploy
  script:
    - './gradlew publish'
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH